#!/usr/bin/env bash
# Verify every version reference matches VERSION (the single source of truth):
#   - include/clogx_version.h  (generated by Makefile/CMake, git-tracked)
#   - vcpkg.json               ("version" field)
#   - Makefile                 (fallback echo when VERSION is missing)
#   - CHANGELOG.md             (## [X.Y.Z] heading + [Unreleased] presence)
# Exits non-zero and lists every mismatch. Run from the repo root.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

V="$(head -n 1 VERSION | tr -d '[:space:]')"
if [[ ! "$V" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "error: VERSION does not look like semver: '$V'" >&2
    exit 1
fi
IFS='.' read -r MAJ MIN PAT <<<"$V"

fail=0
check() {
    if ! "$@"; then
        echo "mismatch: $*" >&2
        fail=1
    fi
}

check grep -q "\"version\": \"$V\"" vcpkg.json
check grep -q "define CLOGX_VERSION_MAJOR $MAJ" include/clogx_version.h
check grep -q "define CLOGX_VERSION_MINOR $MIN" include/clogx_version.h
check grep -q "define CLOGX_VERSION_PATCH $PAT" include/clogx_version.h
check grep -q "define CLOGX_VERSION_STRING \"$V\"" include/clogx_version.h
check grep -q "else echo \"$V\"; fi" Makefile
check grep -q "^## \[$V\] - " CHANGELOG.md
check grep -q "^## \[Unreleased\]" CHANGELOG.md

exit "$fail"
