#!/usr/bin/env bash
# Release helper: bump the unified version, update every version reference,
# and create an annotated tag.
#
# VERSION (repo root) is the single source of truth; all other version
# references are derived from it. This script keeps them in sync:
#   - VERSION
#   - include/clogx_version.h        (generated by Makefile/CMake, git-tracked)
#   - vcpkg.json                     (hard-coded "version")
#   - Makefile                       (fallback echo when VERSION is missing)
#   - CHANGELOG.md                   (## [Unreleased] heading + compare links)
#
# Usage: ./scripts/release.sh [--dry-run] [--push] [patch|minor|major|X.Y.Z]
#
# Bump selection (in priority order):
#   1. explicit argument patch|minor|major|X.Y.Z
#   2. auto: BREAKING CHANGE commit -> major, feat -> minor, else patch

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

RELEASE_FILES="VERSION include/clogx_version.h vcpkg.json Makefile CHANGELOG.md"

on_error() {
    local tag="${TAG:-}"
    echo "error: release aborted partway; version files may have been modified." >&2
    echo "inspect with 'git status'. Roll back with:" >&2
    echo "  git checkout -- $RELEASE_FILES" >&2
    if [ -n "$tag" ]; then
        echo "  git tag -d $tag" >&2
    fi
}
trap 'on_error' ERR

DRY_RUN=0
PUSH=0
BUMP=""

for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=1 ;;
        --push) PUSH=1 ;;
        patch|minor|major) BUMP="$arg" ;;
        *)
            if [[ "$arg" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                BUMP="$arg"
            else
                echo "error: unexpected argument '$arg'" >&2
                echo "usage: $0 [--dry-run] [--push] [patch|minor|major|X.Y.Z]" >&2
                exit 2
            fi
            ;;
    esac
done

if [ ! -f VERSION ]; then
    echo "error: VERSION file not found (run from repo root)" >&2
    exit 1
fi

# --- pre-flight checks ------------------------------------------------------

# Only the five version files may be dirty; refuse to mix release commits
# with unrelated in-progress work.
dirty="$(git status --porcelain | grep -v -E '^(M| M) (VERSION|include/clogx_version\.h|vcpkg\.json|Makefile|CHANGELOG\.md)$' || true)"
if [ -n "$dirty" ]; then
    echo "error: working tree has changes outside the version files:" >&2
    echo "$dirty" >&2
    echo "commit or stash them first, or run with --dry-run to preview" >&2
    exit 1
fi

# Refuse to tag behind the remote: a pushed release tag must be an ancestor
# of origin's tip so the tag points at a commit reachable upstream.
if [ "$DRY_RUN" = 0 ]; then
    if ! git rev-parse --verify -q refs/remotes/origin/master >/dev/null; then
        echo "error: no origin/master tracking ref; fetch first" >&2
        exit 1
    fi
    local_head="$(git rev-parse HEAD)"
    remote_head="$(git rev-parse refs/remotes/origin/master)"
    if [ "$local_head" != "$remote_head" ]; then
        echo "error: local HEAD ($(git rev-parse --short "$local_head")) is not origin/master ($(git rev-parse --short "$remote_head"))" >&2
        echo "run 'git fetch && git rebase origin/master' (or --dry-run to preview)" >&2
        exit 1
    fi
fi

CURRENT="$(head -n 1 VERSION | tr -d '[:space:]')"
if [[ ! "$CURRENT" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "error: VERSION does not look like semver: '$CURRENT'" >&2
    exit 1
fi

IFS='.' read -r CUR_MAJ CUR_MIN CUR_PAT <<<"$CURRENT"

# --- determine new version -------------------------------------------------

resolve_bump() {
    local last_tag
    last_tag="$(git tag --sort=-v:refname | head -n 1 || true)"
    if [ -z "$last_tag" ]; then
        echo "patch"
        return
    fi
    if git log "${last_tag}..HEAD" --format=%B 2>/dev/null | grep -q "BREAKING CHANGE"; then
        echo "major"
    elif git log "${last_tag}..HEAD" --oneline 2>/dev/null | grep -qE "(^|[ ])(feat|perf)(\(|:)"; then
        echo "minor"
    else
        echo "patch"
    fi
}

if [[ "$BUMP" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    NEW="$BUMP"
else
    [ -z "$BUMP" ] && BUMP="$(resolve_bump)"
    case "$BUMP" in
        major) NEW="$((CUR_MAJ + 1)).0.0" ;;
        minor) NEW="$CUR_MAJ.$((CUR_MIN + 1)).0" ;;
        patch) NEW="$CUR_MAJ.$CUR_MIN.$((CUR_PAT + 1))" ;;
        *) echo "error: bad bump '$BUMP'" >&2 && exit 2 ;;
    esac
fi

if [ "$NEW" = "$CURRENT" ]; then
    echo "error: version unchanged ($CURRENT). Nothing to release." >&2
    exit 1
fi

IFS='.' read -r NEW_MAJ NEW_MIN NEW_PAT <<<"$NEW"
RELEASE_DATE="$(date +%F)"
REMOTE_URL="$(git remote get-url origin 2>/dev/null || true)"
REPO="$(printf '%s\n' "$REMOTE_URL" | sed -nE 's#.*github\.com[:/]([^/]+/[^/.]+)(\.git)?$#\1#p')"
[ -z "$REPO" ] && REPO="quintin-lee/clogx"
TAG="v$NEW"

if git tag | grep -qx "$TAG"; then
    echo "error: tag '$TAG' already exists" >&2
    exit 1
fi

echo "Version: $CURRENT -> $NEW  ($BUMP bump)"
echo "Tag:     $TAG"
echo "Date:    $RELEASE_DATE"
echo "Remote:  $REPO"
[ "$DRY_RUN" = 1 ] && echo "--- DRY RUN: no files will be modified ---"

# --- update version references --------------------------------------------

run() {
    if [ "$DRY_RUN" = 1 ]; then
        echo "  would run: $*"
    else
        eval "$@"
    fi
}

echo ""
echo "Updating version references:"

# 1. VERSION (source of truth)
run "printf '%s\n' '$NEW' > VERSION"
echo "  VERSION -> $NEW"

# 2. include/clogx_version.h (mirrors the Makefile generator exactly)
run "printf '#ifndef CLOGX_VERSION_H\\n#define CLOGX_VERSION_H\\n\\n#define CLOGX_VERSION_MAJOR $NEW_MAJ\\n#define CLOGX_VERSION_MINOR $NEW_MIN\\n#define CLOGX_VERSION_PATCH $NEW_PAT\\n#define CLOGX_VERSION_STRING \\\"$NEW\\\"\\n\\n#endif\\n' > include/clogx_version.h"
echo "  include/clogx_version.h -> $NEW_MAJ.$NEW_MIN.$NEW_PAT ($NEW)"

# 3. vcpkg.json
run "sed -i 's/\"version\": \"$CURRENT\"/\"version\": \"$NEW\"/' vcpkg.json"
echo "  vcpkg.json -> $NEW"

# 4. Makefile fallback (only the `else echo "x.y.z"` branch, not libyaml versions)
run "sed -i 's/else echo \"$CURRENT\"; fi/else echo \"$NEW\"; fi/' Makefile"
echo "  Makefile fallback -> $NEW"

# 5. CHANGELOG.md: rename [Unreleased] heading, insert a fresh empty
#    [Unreleased] section, update the compare link, add the new release link.
run "sed -i '0,/^## \\[Unreleased\\]\$/s//## [$NEW] - $RELEASE_DATE/' CHANGELOG.md"
run "awk -v nv='## [Unreleased]' '/^All notable changes/ { print; print \"\"; print nv; next } { print }' CHANGELOG.md > CHANGELOG.md.tmp && mv CHANGELOG.md.tmp CHANGELOG.md"
run "sed -i \"s|compare/v${CURRENT}\\.\\.\\.HEAD|compare/v${NEW}...HEAD|\" CHANGELOG.md"
run "sed -i \"/^\\[${CURRENT}\\]: /i [$NEW]: https://github.com/${REPO}/releases/tag/v$NEW\" CHANGELOG.md"
echo "  CHANGELOG.md -> ## [$NEW] - $RELEASE_DATE + links"

[ "$DRY_RUN" = 1 ] && { echo ""; echo "Dry run complete. Re-run without --dry-run to apply."; exit 0; }

# --- commit + tag ----------------------------------------------------------

echo ""
echo "Creating release commit and annotated tag..."
git add VERSION include/clogx_version.h vcpkg.json Makefile CHANGELOG.md
git commit -m "chore(release): 🚀 release $TAG"

# Extract the new changelog section as the tag message.
awk -v tag="$NEW" '
    $0 == "## [" tag "] -" || $0 ~ "^## \\[" tag "\\] -" { in_sec = 1; next }
    in_sec && /^## / { exit }
    in_sec { print }
' CHANGELOG.md > /tmp/clogx-release-notes.txt

if [ -s /tmp/clogx-release-notes.txt ]; then
    git tag -a "$TAG" -F /tmp/clogx-release-notes.txt
else
    git tag -a "$TAG" -m "clogx $NEW"
fi
rm -f /tmp/clogx-release-notes.txt

echo "Tag $TAG created (annotated)."

if [ "$PUSH" = 1 ]; then
    branch="$(git rev-parse --abbrev-ref HEAD)"
    git push origin "$branch"
    git push origin "$TAG"
    echo "Pushed $branch and $TAG to origin."
else
    echo "Not pushed. Use --push to publish, or run:"
    echo "  git push origin $(git rev-parse --abbrev-ref HEAD) && git push origin $TAG"
fi
